const {test}=require('node:test'),assert=require('node:assert/strict');
const {readFileSync,readdirSync}=require('node:fs'),{join}=require('node:path');const {PGlite}=require('@electric-sql/pglite'),{pg_trgm}=require('@electric-sql/pglite/contrib/pg_trgm');
const id=n=>`a6000000-0000-4000-a000-${String(n).padStart(12,'0')}`,sqlstr=s=>"'"+s.replaceAll("'","''")+"'";
test('closeout SQL: bounded quotation search, owner privacy, category administration and safe public filters',async t=>{
  const db=new PGlite({extensions:{pg_trgm}}),admin=id(1),sales=id(2),writer=id(3),other=id(4),co=id(10),foreign=id(11),part=id(20),hidden=id(21),alien=id(22),customer=id(30),category=id(40),token='a'.repeat(64);
  try{
    await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;create table auth.users(id uuid primary key,aud text,role text,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid$$;grant usage on schema auth,storage to anon,authenticated;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text,metadata jsonb);alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to anon,authenticated;create function storage.foldername(name text) returns text[] language sql immutable as $$select (string_to_array(name,'/'))[1:array_length(string_to_array(name,'/'),1)-1]$$;`);
    for(const f of readdirSync(join(__dirname,'../supabase/migrations')).filter(f=>f.endsWith('.sql')).sort()){
      if(f.startsWith('202610060006'))await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${admin}','admin@test.example',now()),('${sales}','sales@test.example',now()),('${writer}','writer@test.example',now()),('${other}','other@test.example',now());insert into public.companies(id,name) values('${co}','A'),('${foreign}','B');insert into public.company_members(company_id,user_id,role,is_primary,can_manage_products) values('${co}','${admin}','admin',true,false),('${co}','${sales}','sales',false,false),('${co}','${writer}','sales',false,true),('${foreign}','${other}','admin',true,false);insert into public.products(id,company_id,serial,name,price,category,catalog_public) values('${part}','${co}','P1','Part',9,'Legacy category',true),('${hidden}','${co}','PRIVATE','Hidden',99,'SECRET CATEGORY',false),('${alien}','${foreign}','OTHER','Foreign',99,'OTHER CATEGORY',true);`);
      await db.exec(readFileSync(join(__dirname,'../supabase/migrations',f),'utf8'));
    }
    await db.exec(readFileSync(join(__dirname,'../supabase/tests/launchpad_closeout.sql'),'utf8'));
    async function as(user,sql,{commit=false}={}){await db.exec(`begin;set local role ${user?'authenticated':'anon'};select set_config('request.jwt.claims','${JSON.stringify(user?{sub:user,aal:'aal1'}:{})}',true);`);try{const r=await db.query(sql);await db.exec(commit?'commit':'rollback');return r.rows;}catch(err){await db.exec('rollback');throw err;}}
    const manage=(user,cat,name,rev,action)=>as(user,`select * from public.manage_company_category('${co}','${cat}',${sqlstr(name)},${rev},'${action}')`,{commit:true}).then(r=>r[0]);
    const history=(user,query='',state='all',cursor=null)=>as(user,`select public.search_company_quotations('${co}',${sqlstr(query)},'${state}',false,${cursor?sqlstr(cursor.updated_at):'null'},${cursor?sqlstr(cursor.id):'null'}) value`).then(r=>r[0].value);
    await t.test('legacy categories preserved, admin-only taxonomy and permissioned staff assignment',async()=>{
      const list=(await as(sales,`select public.list_company_categories('${co}') value`))[0].value;assert(list.some(c=>c.name==='Legacy category'));assert(!list.some(c=>c.name==='OTHER CATEGORY'));
      await assert.rejects(manage(sales,category,'Tools',0,'create'),/Administrator/);await assert.rejects(manage(writer,category,'Tools',0,'create'),/Administrator/);await assert.rejects(manage(other,category,'Tools',0,'create'),/Administrator/);
      const c=await manage(admin,category,'Tools',0,'create');assert.equal((await manage(admin,category,'Tools',0,'create')).id,c.id);
      await as(writer,`update public.products set category='tools' where id='${part}'`,{commit:true});assert.equal((await db.query(`select category from public.products where id='${part}'`)).rows[0].category,'Tools');
      await assert.rejects(as(writer,`update public.products set category='Not created' where id='${part}'`,{commit:true}),/administrator/);
      assert.equal((await as(sales,`update public.products set category='Tools' where id='${part}' returning id`,{commit:true})).length,0);
      const renamed=await manage(admin,category,'Hardware',c.revision,'rename');assert.equal((await db.query(`select category from public.products where id='${part}'`)).rows[0].category,'Hardware');
      await assert.rejects(manage(admin,category,'Stale',c.revision,'rename'),/changed/);
      const archived=await manage(admin,category,'Hardware',renamed.revision,'archive');await as(writer,`update public.products set price=10,category='Hardware' where id='${part}'`,{commit:true});await assert.rejects(as(writer,`update public.products set category='Hardware' where id='${hidden}'`,{commit:true}),/inactive/);await manage(admin,category,'Hardware',archived.revision,'restore');
      await as(admin,`select public.import_products_batch('${co}','${id(90)}','[{"row_number":1,"serial":"CSV-CATEGORY","name":"CSV","price":"1.00","category":"Imported category"}]'::jsonb)`,{commit:true});assert((await as(sales,`select public.list_company_categories('${co}') value`))[0].value.some(c=>c.name==='Imported category'));
    });
    await t.test('customer owners shown to admins, other staff/private-company contacts remain inaccessible',async()=>{
      await as(sales,`select public.save_account_profile('Staff Name','+60123456789',1)`,{commit:true});await as(sales,`insert into public.customers(id,company_id,name) values('${customer}','${co}','Client')`,{commit:true});
      const list=(await as(admin,`select public.search_company_customers('${co}','Staff Name') value`))[0].value;assert.equal(list.total,1);assert.equal(list.items[0].owner_name,'Staff Name');assert.equal(list.items[0].owner_email,'sales@test.example');
      assert.equal((await as(writer,`select public.search_company_customers('${co}','Staff Name') value`))[0].value.total,0);await assert.rejects(as(other,`select public.search_company_customers('${co}')`),/access denied/);await assert.rejects(as(null,`select public.search_company_customers('${co}')`),/permission denied/);
      assert.equal((await as(admin,`update public.customers set name='Override' where id='${customer}' returning id`,{commit:true})).length,0);
    });
    await t.test('50-item keyset history and whole-company filters still obey own/admin RLS',async()=>{
      await db.exec(`insert into public.quotations(id,company_id,created_by,number,quote_date,customer_name,status,updated_at) select ('a6000000-0000-4000-a000-'||lpad((10000+n)::text,12,'0'))::uuid,'${co}','${sales}','SEARCH-'||n,current_date,case when n=105 then '100%_safe' else 'Client' end,case when n%2=0 then 'paid' else 'pending' end,'2026-01-01' from generate_series(1,120)n;insert into public.quotations(id,company_id,created_by,number,quote_date,customer_name) values('${id(999)}','${co}','${writer}','PEER',current_date,'Peer');`);
      let cursor=null,seen=new Set(),more=true;while(more){const page=await history(sales,'SEARCH-','all',cursor);assert(page.items.length<=50);for(const q of page.items){assert(!seen.has(q.id));seen.add(q.id);}cursor=page.cursor;more=page.has_more;}assert.equal(seen.size,120);
      assert.equal((await history(sales,'SEARCH-105')).items.length,1);assert.equal((await history(sales,'100%_safe')).items.length,1);assert.equal((await history(sales,'SEARCH-','paid')).items.length,50);assert.equal((await history(sales,'PEER')).items.length,0);assert.equal((await history(admin,'PEER')).items.length,1);
      await assert.rejects(history(other),/access denied/);await assert.rejects(history(null),/permission denied/);
    });
    await t.test('company/public categories are globally filtered, public options reveal only link-authorized products',async()=>{
      const page=(await as(sales,`select public.search_company_products('${co}','',null,null,'Hardware') value`))[0].value;assert.equal(page.total,1);assert.equal(page.items[0].id,part);
      await as(sales,`select public.create_catalog_link('${co}','${id(98)}','${token}','',null)`,{commit:true});
      const p=(await as(null,`select public.read_public_catalog('${token}','',null,null,'Hardware') value`))[0].value;assert.equal(p.total,1);assert.deepEqual(p.categories,['Hardware']);assert(!JSON.stringify(p).includes('price'));assert(!p.categories.includes('SECRET CATEGORY'));
      assert.equal((await as(null,`select public.read_public_catalog('${token}','',null,null,'SECRET CATEGORY') value`))[0].value.total,0);await assert.rejects(as(null,`select public.list_company_categories('${co}')`),/permission denied/);
      await db.exec(`update public.companies set service_state='suspended' where id='${co}'`);await assert.rejects(history(admin),/access denied/);await assert.rejects(as(sales,`select public.list_company_categories('${co}')`),/access denied/);await assert.rejects(as(null,`select public.read_public_catalog('${token}','',null,null,null)`),/unavailable/);
    });
  }finally{await db.close();}
});
