const {test}=require('node:test'),assert=require('node:assert/strict'),{readFileSync,readdirSync}=require('node:fs'),{join}=require('node:path');
const {PGlite}=require('@electric-sql/pglite'),{pg_trgm}=require('@electric-sql/pglite/contrib/pg_trgm');
const id=n=>`a7000000-0000-4000-a000-${String(n).padStart(12,'0')}`,lit=s=>s==null?'null':"'"+String(s).replaceAll("'","''")+"'";
test('filter batch: 30-item pages, inclusive date guard, creator/customer privacy and history access',async t=>{
  const db=new PGlite({extensions:{pg_trgm}}),admin=id(1),sales=id(2),peer=id(3),other=id(4),co=id(10),foreign=id(11),token='a'.repeat(64);
  try{
    await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;create table auth.users(id uuid primary key,aud text,role text,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid$$;grant usage on schema auth,storage to anon,authenticated;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text,metadata jsonb);alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to anon,authenticated;create function storage.foldername(name text) returns text[] language sql immutable as $$select (string_to_array(name,'/'))[1:array_length(string_to_array(name,'/'),1)-1]$$;`);
    for(const f of readdirSync(join(__dirname,'../supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync(join(__dirname,'../supabase/migrations',f),'utf8'));
    await db.exec(readFileSync(join(__dirname,'../supabase/tests/launchpad_filters.sql'),'utf8'));
    await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${admin}','admin@test.example',now()),('${sales}','sales@test.example',now()),('${peer}','peer@test.example',now()),('${other}','other@test.example',now());insert into public.companies(id,name) values('${co}','A'),('${foreign}','B');insert into public.company_members(company_id,user_id,role,is_primary) values('${co}','${admin}','admin',true),('${co}','${sales}','sales',false),('${co}','${peer}','sales',false),('${foreign}','${other}','admin',true);
      insert into public.quotations(id,company_id,created_by,number,quote_date,customer_name,status,updated_at) select ('a7000000-0000-4000-a000-'||lpad((10000+n)::text,12,'0'))::uuid,'${co}','${sales}','OLD-'||n,'2000-01-01','Manual historic customer',case when n%2=0 then 'paid' else 'pending' end,'2000-01-01' from generate_series(1,80)n;
      insert into public.quotations(id,company_id,created_by,number,quote_date,customer_name,status) values('${id(100)}','${co}','${peer}','PEER','2000-01-30','Private peer customer','pending'),('${id(101)}','${co}','${sales}','END','2000-01-30','Edge customer','success'),('${id(102)}','${co}','${sales}','OUT','2000-01-31','Out customer','pending'),('${id(103)}','${foreign}','${other}','ALIEN','2000-01-01','Foreign customer','pending');
      insert into public.products(id,company_id,serial,name,price,catalog_public) select ('a7000000-0000-4000-a000-'||lpad((20000+n)::text,12,'0'))::uuid,'${co}','P-'||n,'Part',9,true from generate_series(1,75)n;`);
    async function as(user,sql,{commit=false}={}){await db.exec(`begin;set local role ${user?'authenticated':'anon'};select set_config('request.jwt.claims','${JSON.stringify(user?{sub:user,aal:'aal1'}:{})}',true);`);try{const result=await db.query(sql);await db.exec(commit?'commit':'rollback');return result.rows;}catch(err){await db.exec('rollback');throw err;}}
    const page=(u,{creator=null,customer=null,start='2000-01-01',end='2000-01-30',status='all',cursor=null,query=''}={})=>as(u,`select public.search_company_quotations('${co}',${lit(query)},'${status}',false,${lit(cursor?.updated_at)},${lit(cursor?.id)},${lit(creator)},${lit(customer)},${lit(start)},${lit(end)}) value`).then(r=>r[0].value);
    const customers=(u,creator=null,query='')=>as(u,`select public.quotation_customer_options('${co}',${lit(creator)},${lit(query)},0) value`).then(r=>r[0].value);
    await t.test('30-item quote keyset pages never repeat or omit records; dates can reach year 2000',async()=>{
      let cursor=null,more=true;const seen=new Set();while(more){const p=await page(sales,{cursor});assert(p.items.length<=30);for(const q of p.items){assert(!seen.has(q.id));seen.add(q.id);}cursor=p.cursor;more=p.has_more;}assert.equal(seen.size,81);assert(seen.has(id(101)));assert(!seen.has(id(102)));assert(!seen.has(id(100)));
      assert.equal((await page(sales,{start:'2000-01-30',end:'2000-01-30'})).items.length,1);assert.equal((await page(admin,{creator:peer})).items[0].number,'PEER');assert.equal((await page(admin,{customer:'Manual historic customer'})).items.length,30);
      await assert.rejects(page(sales,{end:'2000-01-31'}),/1-30/);await assert.rejects(page(sales,{start:null}),/1-30/);await assert.rejects(page(sales,{start:'2000-01-30',end:'2000-01-01'}),/1-30/);
    });
    await t.test('customer candidates and actor filters do not expose other employees or companies',async()=>{
      assert((await customers(sales)).items.includes('Manual historic customer'));assert(!(await customers(sales)).items.includes('Private peer customer'));assert.deepEqual((await customers(admin,peer)).items,['Private peer customer']);
      await assert.rejects(page(sales,{creator:peer}),/access denied/);await assert.rejects(customers(sales,peer),/access denied/);await assert.rejects(page(other),/access denied/);await assert.rejects(page(null),/permission denied/);await assert.rejects(customers(null),/permission denied/);
      await as(sales,`insert into public.customers(company_id,name) values('${co}','Own contact')`,{commit:true});await as(peer,`insert into public.customers(company_id,name) values('${co}','Peer contact')`,{commit:true});
      const ownerQuery=(u,owner)=>as(u,`select public.search_company_customers('${co}','',false,0,${lit(owner)}) value`).then(r=>r[0].value);
      assert.equal((await ownerQuery(admin,peer)).items[0].name,'Peer contact');assert.equal((await ownerQuery(admin,other)).total,0);await assert.rejects(ownerQuery(sales,peer),/access denied/);assert.equal((await ownerQuery(sales,null)).total,1);
    });
    await t.test('internal, share-management and anonymous product pages consistently bound to 30',async()=>{
      const p=(await as(sales,`select public.search_company_products('${co}','',null,null,null) value`))[0].value;assert.equal(p.items.length,30);assert(p.has_more);
      assert.equal((await as(sales,`select public.search_catalog_share_products('${co}') value`))[0].value.items.length,30);
      await as(sales,`select public.save_account_profile('Sales','+60123456789',1)`,{commit:true});await as(sales,`select public.create_catalog_link('${co}','${id(300)}','${token}','',null)`,{commit:true});
      const guest=(await as(null,`select public.read_public_catalog('${token}','',null,null,null) value`))[0].value;assert.equal(guest.items.length,30);assert(guest.has_more);assert(!JSON.stringify(guest).includes('price'));
      await db.exec(`update public.company_members set active=false where user_id='${sales}'`);await assert.rejects(page(sales),/access denied/);await assert.rejects(customers(sales),/access denied/);await assert.rejects(as(null,`select public.read_public_catalog('${token}','',null,null,null)`),/unavailable/);
    });
  }finally{await db.close();}
});
