"use client";
import {useEffect,useRef,useState} from 'react';
import {createClient} from '../../../lib/supabase/client';
import {readCategories} from '../../../lib/supabase/categories';
import {readPriceSnapshots,applyPriceBatches,PRICE_APPLY_TERMINAL} from '../../../lib/supabase/price-changes';
import {parseCsv} from '../../../lib/product-csv';
import {guessPriceMapping,previewPriceCsv,priceReportCsv,PRICE_STATUS} from '../../../lib/product-price-csv';
import {addPriceEditorProducts,priceEditorProduct,validatePriceEditorRows,preparePriceEditorRows,refreshPriceEditorBases,exportPriceEditorCsv} from '../../../lib/price-editor';
import CategoryFilter from '../../CategoryFilter';
import {formatMoney,moneyToCents} from '../../quotation-utils';
import {downloadFile} from '../../share';

export default function PriceEditor({context,blocked=false,onBusyChange}){
  const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[category,setCategory]=useState(null),[categories,setCategories]=useState([]),[catalog,setCatalog]=useState({items:[],has_more:false}),[catalogPage,setCatalogPage]=useState(0),[loading,setLoading]=useState(false),[catalogError,setCatalogError]=useState('');
  const [drafts,setDrafts]=useState([]),[tablePage,setTablePage]=useState(0),[preview,setPreview]=useState(null),[results,setResults]=useState({}),[busy,setBusy]=useState(false),[begun,setBegun]=useState(false),[applying,setApplying]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [text,setText]=useState(''),[filename,setFilename]=useState(''),[delimiter,setDelimiter]=useState(','),[parsed,setParsed]=useState(null),[mapping,setMapping]=useState({});
  const alive=useRef(true),working=useRef(false),stop=useRef(false),started=useRef(false),job=useRef(null),resultRef=useRef({}),sequence=useRef(0),cursors=useRef([null]);
  const locked=busy||blocked||begun,dirty=drafts.length>0;
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;stop.current=true;++sequence.current;};},[]);
  async function run(task){if(working.current||blocked)return;working.current=true;setBusy(true);onBusyChange?.(true);setError('');setMessage('');try{await task();}catch(err){if(alive.current)setError(err.message||'操作未确认，表内输入仍保留。');}finally{working.current=false;if(alive.current){setBusy(false);onBusyChange?.(false);}}}
  async function loadCatalog(){if(!open||working.current)return;const version=++sequence.current;setLoading(true);setCatalogError('');try{const cursor=cursors.current[catalogPage],client=createClient(),r=await client.rpc('search_company_products',{target_company:context.companyId,search_text:query,after_created:cursor?.created_at||null,after_id:cursor?.id||null,category_filter:category});if(r.error)throw r.error;const cats=await readCategories(client,context.companyId);if(version===sequence.current){setCatalog({...r.data,items:r.data.items.map(priceEditorProduct)});setCategories(cats);}}catch(err){if(version===sequence.current){setCatalog({items:[],has_more:false});setCatalogError(err.message);}}finally{if(version===sequence.current)setLoading(false);}}
  useEffect(()=>{if(!open)return;const timer=setTimeout(()=>void loadCatalog(),200);return()=>{clearTimeout(timer);++sequence.current;};},[open,query,category,catalogPage]);
  useEffect(()=>{const leave=e=>{if(dirty||busy||started.current){e.preventDefault();e.returnValue='';}};const link=e=>{const a=e.target.closest?.('a[href]');if(e.defaultPrevented||!a||a.hasAttribute('download')||a.target==='_blank')return;if((dirty||busy||started.current)&&(busy||!window.confirm('离开将放弃调价表输入／本页进度；已提交的价格与记录保留，不会自动回滚。继续？'))){e.preventDefault();e.stopPropagation();}};window.addEventListener('beforeunload',leave);document.addEventListener('click',link,true);return()=>{window.removeEventListener('beforeunload',leave);document.removeEventListener('click',link,true);};},[dirty,busy]);
  function invalidate(){setPreview(null);job.current=null;setResults({});resultRef.current={};setError('');setMessage('');}
  function add(products){if(locked)return;try{const next=addPriceEditorProducts(drafts,products);invalidate();setDrafts(next);setMessage(`已选 ${next.length} 项，尚未修改云端价格。`);}catch(err){setError(err.message);}}
  function edit(key,value){if(locked)return;invalidate();setDrafts(prev=>prev.map(d=>d.key===key?{...d,newPrice:value}:d));}
  function remove(key){if(locked)return;invalidate();setDrafts(prev=>{const next=prev.filter(d=>d.key!==key);setTablePage(n=>Math.min(n,Math.max(0,Math.ceil(next.length/30)-1)));return next;});}
  function newTask(){if(working.current||blocked)return;if(started.current&&!window.confirm('开始新任务会解锁输入并丢弃本页处理结果；已改价格不会回滚。请保留结果并重新检查原价。继续？'))return;started.current=false;setBegun(false);stop.current=false;invalidate();setMessage('输入已解锁。请重读原价后重新检查，已改价格没有回滚。');}
  async function check(){if(locked||!drafts.length)return;await run(async()=>{invalidate();const rows=validatePriceEditorRows(drafts),products=await readPriceSnapshots(createClient(),context.companyId,rows.filter(r=>!r.error).map(r=>r.serial),{stopped:()=>!alive.current});if(!alive.current)return;const hydrated=refreshPriceEditorBases(drafts,products).map((d,i)=>drafts[i].product?drafts[i]:d);setDrafts(hydrated);setPreview(preparePriceEditorRows(drafts,products));job.current=crypto.randomUUID();setMessage('检查完成，尚未写入价格。只有可调价行会提交，其他行可修正后重新检查。');});}
  async function refreshBases(){if(locked||!drafts.length)return;if(!window.confirm('重新读取会以最新云端原价／版本替换表内原价快照，但保留你填写的新价。请再次检查确认；不会修改云端价格。继续？'))return;await run(async()=>{const products=await readPriceSnapshots(createClient(),context.companyId,drafts.filter(d=>d.serial.trim()&&d.serial.trim().length<=120).map(d=>d.serial),{stopped:()=>!alive.current});if(alive.current){setDrafts(refreshPriceEditorBases(drafts,products));invalidate();setMessage('原价快照已更新，新价输入保留，请重新检查。');}});}
  async function apply(){if(working.current||blocked||!preview||!job.current)return;const pending=preview.filter(r=>r.status==='ready'&&!PRICE_APPLY_TERMINAL.has(resultRef.current[r.row_number]?.status));if(!pending.length||!window.confirm(`确认提交 ${pending.length} 项新价格？不改其他产品资料或历史报价，冲突不会覆盖。`))return;started.current=true;setBegun(true);stop.current=false;setApplying(true);await run(async()=>{try{await applyPriceBatches(createClient(),context.companyId,job.current,pending,{results:resultRef.current,stopped:()=>stop.current,onProgress:rows=>{if(alive.current)setResults(rows);}});if(alive.current)setMessage(stop.current?'已暂停，已提交行保留，可继续。':'本次处理完成；失败／冲突行可开始新任务、重读原价后再检查。');}finally{if(alive.current)setApplying(false);}});}
  function parse(content,separator){const p=parseCsv(content,separator);setParsed(p);setMapping(guessPriceMapping(p.headers));}
  async function choose(file){if(!file||locked)return;await run(async()=>{if(!/\.csv$/i.test(file.name)||file.size>5*1024*1024)throw new Error('请选择不超过 5MB 的 CSV UTF-8。');const content=await file.text();if(content.includes('\uFFFD'))throw new Error('文件不是 UTF-8，请重新导出。');if(!alive.current)return;setText(content);setFilename(file.name);setParsed(null);parse(content,delimiter);});}
  async function importCsv(){if(locked||!parsed)return;if(drafts.length&&!window.confirm('导入将替换当前待调价表。尚未提交的输入会被替换，云端价格不会修改。继续？'))return;await run(async()=>{const rows=previewPriceCsv(parsed,mapping),next=rows.map(r=>({key:crypto.randomUUID(),serial:r.serial,newPrice:r.raw_price,product:null}));const products=await readPriceSnapshots(createClient(),context.companyId,rows.filter(r=>r.serial&&r.serial.length<=120).map(r=>r.serial),{stopped:()=>!alive.current});if(alive.current){invalidate();setDrafts(refreshPriceEditorBases(next,products));setTablePage(0);setMessage('CSV 已导入表内，可改新价、移除重复行，未匹配编号可修正；检查并确认前不写云端。');}});}
  function catalogFilter(nextQuery,nextCategory){if(locked)return;++sequence.current;setCatalog({items:[],has_more:false});setLoading(true);cursors.current=[null];setCatalogPage(0);setQuery(nextQuery);setCategory(nextCategory);}
  function nextCatalog(next){if(locked||loading||next<0)return;if(next>catalogPage)cursors.current[next]=catalog.cursor;setCatalog({items:[],has_more:false});setLoading(true);setCatalogPage(next);}
  function exportDraft(){try{downloadFile(new File([exportPriceEditorCsv(drafts)],'jomsales-price-editor.csv',{type:'text/csv;charset=utf-8'}));setMessage('已导出待调价 CSV；可直接导回调价表／CSV 调价。Excel 中不要修改编号编码列。');}catch(err){setError(err.message);}}
  const pending=preview?.filter(r=>r.status==='ready'&&!PRICE_APPLY_TERMINAL.has(results[r.row_number]?.status)).length||0,updated=Object.values(results).filter(r=>r.status==='updated').length;
  const amount=v=>v==null?'—':formatMoney(moneyToCents(v));
  return <details className="accountCard" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>批量调价表（管理员）</summary>
    <p>选产品 → 填新价 → 检查 → 确认。只改价格，不新增产品；最多 10,000 项，每页显示 30 项。</p>
    {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    <label>搜索调价产品<input aria-label="搜索调价产品" maxLength={240} value={query} disabled={locked} onChange={e=>catalogFilter(e.target.value,category)}/></label>
    <CategoryFilter label="调价产品分类" categories={categories} value={category} onChange={value=>catalogFilter(query,value)} disabled={locked}/>
    <button disabled={busy||blocked||loading} onClick={()=>void loadCatalog()}>刷新调价产品</button>{loading&&<p role="status">正在读取调价产品…</p>}{catalogError&&<p role="alert">{catalogError}</p>}
    {!loading&&!catalog.items.length&&<p>没有符合条件的调价产品。</p>}
    <button disabled={locked||loading||!catalog.items.length} onClick={()=>add(catalog.items)}>加入当前页产品（最多 30 项）</button>
    {catalog.items.map(p=><article className="teamRow" key={p.id}><div><strong>{p.serial} · {p.name}</strong><p>{p.category||'未分类'} · {amount(p.price)}</p></div><button disabled={locked||drafts.some(d=>d.serial.trim().toLowerCase()===p.serial.toLowerCase())} onClick={()=>add([p])}>加入调价：{p.serial}</button></article>)}
    <div className="cloudButtons"><button disabled={locked||loading||!catalogPage} onClick={()=>nextCatalog(catalogPage-1)}>上一页调价产品</button><span>产品第 {catalogPage+1} 页 · 每页 30 项</span><button disabled={locked||loading||!catalog.has_more} onClick={()=>nextCatalog(catalogPage+1)}>下一页调价产品</button></div>
    <details><summary>CSV 导入／导出</summary><label>导入调价表 CSV<input type="file" accept=".csv,text/csv" disabled={locked} onChange={e=>{const file=e.target.files?.[0];e.target.value='';void choose(file);}}/></label>
      {text&&<><p>{filename}</p><label>表格 CSV 分隔符<select aria-label="表格 CSV 分隔符" disabled={locked} value={delimiter} onChange={e=>{setDelimiter(e.target.value);setParsed(null);try{parse(text,e.target.value);setError('');}catch(err){setError(err.message);}}}><option value=",">逗号</option><option value=";">分号</option><option value={'\t'}>Tab</option></select></label></>}
      {parsed&&<>{[['serial','表格 CSV 编号列'],['price','表格 CSV 新价列']].map(([key,label])=><label key={key}>{label}<select aria-label={label} disabled={locked} value={mapping[key]??-1} onChange={e=>setMapping({...mapping,[key]:Number(e.target.value)})}><option value={-1}>请选择对应列</option>{parsed.headers.map((header,i)=><option value={i} key={i}>{header}</option>)}</select></label>)}<button disabled={locked} onClick={()=>void importCsv()}>导入到调价表（不保存）</button></>}
      <button disabled={busy||blocked||!drafts.length} onClick={exportDraft}>导出待调价表 CSV</button>
    </details>
    <h3>待调价清单（{drafts.length} 项）</h3>{begun&&<p>任务已开始，输入已锁定。失败时重试；需编辑请开始新任务，已提交价格不会回滚。</p>}
    {drafts.slice(tablePage*30,tablePage*30+30).map((d,i)=>{const index=tablePage*30+i,row=preview?.[index],outcome=results[index+1];return <article className="priceEditorRow" key={d.key}><strong>第 {index+1} 行 · {d.serial||'编号未填写'}</strong>
      {!d.product&&<label>未匹配编号<input aria-label={`修正编号：第 ${index+1} 行`} disabled={locked} maxLength={120} value={d.serial} onChange={e=>{if(locked)return;invalidate();setDrafts(prev=>prev.map(r=>r.key===d.key?{...r,serial:e.target.value}:r));}}/></label>}
      <p>{d.product?.name||'待匹配产品'} · 原价 {amount(d.product?.price)}</p><label>新价（RM）<input aria-label={`表格新价：${d.serial}（第 ${index+1} 行）`} type="text" inputMode="decimal" disabled={locked} value={d.newPrice} onChange={e=>edit(d.key,e.target.value)}/></label>
      <button disabled={locked} onClick={()=>remove(d.key)}>移除调价行 {index+1}</button>{row&&<p>{row.error||outcome?.message||PRICE_STATUS[outcome?.status||row.status]}</p>}
    </article>;})}
    {!!drafts.length&&<><div className="cloudButtons"><button disabled={busy||blocked||!tablePage} onClick={()=>setTablePage(n=>n-1)}>上一页待调价</button><span>待调价第 {tablePage+1} 页 · 每页 30 项</span><button disabled={busy||blocked||(tablePage+1)*30>=drafts.length} onClick={()=>setTablePage(n=>n+1)}>下一页待调价</button></div>
      <div className="cloudButtons"><button disabled={locked} onClick={()=>void check()}>检查调价表</button><button disabled={locked} onClick={()=>void refreshBases()}>重读表内原价（保留新价）</button><button disabled={busy||blocked||!pending} onClick={()=>void apply()}>{begun?'继续／重试调价表':'确认提交调价表'}</button>{applying&&<button onClick={()=>{stop.current=true;}}>当前批次完成后暂停表格调价</button>}
        <button disabled={busy||blocked} onClick={newTask}>开始新的表格调价任务</button><button disabled={locked} onClick={()=>{if(window.confirm('清空待调价表？未提交输入将被放弃。')){invalidate();setDrafts([]);setTablePage(0);}}}>清空待调价表</button>
        {preview&&<button disabled={busy||blocked} onClick={()=>downloadFile(new File([priceReportCsv(preview,results)],'jomsales-price-editor-results.csv',{type:'text/csv;charset=utf-8'}))}>下载调价表检查／结果</button>}
      </div>{preview&&<p role="status">可提交 {pending} · 已确认调价 {updated} · 跳过／冲突 {preview.filter(r=>!['ready','unchanged'].includes(r.status)).length+Object.values(results).filter(r=>['conflict','unavailable','failed'].includes(r.status)).length} · 相同价格 {preview.filter(r=>r.status==='unchanged').length}</p>}
    </>}
  </details>;
}
